name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Build SWEB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Build Directory
        run: "mkdir sweb"
      - name: Build SWEB
        run: "cd sweb && cmake .. && make -j"
